name: make hosts file

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make common hosts file
        run: |
          cat source/common.txt | grep -v '#' | grep -v -e '^[[:space:]]*$' | awk '{print "0.0.0.0 "$1}' | sort > data/common
          cat data/common | uniq -d

      - name: commit adult hosts file
        run: |
          git clone https://github.com/StevenBlack/hosts stevenblack --depth 1
          cd stevenblack || exit
          rm -rf data/* extensions/social extensions/gambling extensions/fakenews
          python updateHostsFile.py -a -e porn -s -m
          cat hosts > ../data/adult
          cd .. && rm -rf stevenblack

      - name: Cuatom resolver
        run: |
          bash utils/crawl.sh

      - name: commit and push
        run: |
          git config --global user.name "rzlamrr"
          git config --global user.email "rzlamrr.dvst@protonmail.com"
          git add .
          git commit -m "update hosts file"
          git push
          
